version: '3.8'

services:
  main-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main-app
    ports: 
      - "${APP_PORT}:8000"
    env_file:
      - .env
    volumes:
      - .:/code/
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:16
    container_name: pg
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pg_data:
